version: '2'
services:
  covideo-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/COVIDeo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=COVIDeo
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
